### PR TITLE
WASM support

### PR DESCRIPTION
**Pull request by kuba--**
This PR contains never compiled to native JS (`never.js`). You can test it out from `never.html` file (which loads `never.js` module), e.g. by running:
```bash
python -m SimpleHTTPServer 8000
# http://localhost:8000/never.html
```

To be able compile never to _wasm_ I had to disable _FFI_,  _dlopen_ and asserts (plus a few cosmetic modifications). That's why in _cmake_ we define a new macro `NO_FFI`.

If you want to compile everything from scratch, here is step by step guide:

- Get the latest sdk: git clone https://github.com/emscripten-core/emsdk.git
```
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
```

- Compile to native JS
```
mkdir build && cd build
emcmake cmake .. -DJS_ONLY=ON 
make
```

- Run
Now you should see `never.js` file in your build directory. You can overwrite `../never.js` and open `never.html`, or modify `never.html` to load `build/never.js` file or load the file in JS console and run:
```
var never = Module.cwrap('never','number',['string']);
never("func main() -> int { 123 }")
```

### CODE REVIEW

**Comment by smaludzi** [comment]
I got the following error while trying to compile. Maybe it is caused by -target wasm32-unknown-emscripten option?

smaludzi@slawek-laptop:~/.../never/build_js$ make
/usr/bin/cmake -H/home/smaludzi/projects/never -B/home/smaludzi/projects/never/build_js --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/smaludzi/projects/never/build_js/CMakeFiles /home/smaludzi/projects/never/build_js/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/smaludzi/projects/never/build_js'
make -f CMakeFiles/nev.dir/build.make CMakeFiles/nev.dir/depend
make[2]: Entering directory '/home/smaludzi/projects/never/build_js'
cd /home/smaludzi/projects/never/build_js && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/smaludzi/projects/never /home/smaludzi/projects/never /home/smaludzi/projects/never/build_js /home/smaludzi/projects/never/build_js /home/smaludzi/projects/never/build_js/CMakeFiles/nev.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/smaludzi/projects/never/build_js'
make -f CMakeFiles/nev.dir/build.make CMakeFiles/nev.dir/build
make[2]: Entering directory '/home/smaludzi/projects/never/build_js'
[  1%] Building C object CMakeFiles/nev.dir/front/scanner.c.o
/home/smaludzi/projects/emsdk/upstream/emscripten/emcc   @CMakeFiles/nev.dir/includes_C.rsp -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -DNDEBUG -DNO_FFI   -o CMakeFiles/nev.dir/front/scanner.c.o   -c /home/smaludzi/projects/never/front/scanner.c
In file included from /home/smaludzi/projects/never/front/scanner.c:20:
In file included from /usr/include/stdio.h:27:
/usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
1 error generated.
emcc: error: '/home/smaludzi/projects/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=15 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/smaludzi/.emscripten_cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -I/usr/local/include -I/usr/include -I/home/smaludzi/projects/never/include -I/home/smaludzi/projects/never/front -I/home/smaludzi/projects/never/back -I/home/smaludzi/projects/never/. -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -DNDEBUG -DNO_FFI -c /home/smaludzi/projects/never/front/scanner.c -Xclang -isystem/home/smaludzi/projects/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/nev.dir/front/scanner.c.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
CMakeFiles/nev.dir/build.make:103: recipe for target 'CMakeFiles/nev.dir/front/scanner.c.o' failed
make[2]: *** [CMakeFiles/nev.dir/front/scanner.c.o] Error 1
make[2]: Leaving directory '/home/smaludzi/projects/never/build_js'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nev.dir/all' failed
make[1]: *** [CMakeFiles/nev.dir/all] Error 2
make[1]: Leaving directory '/home/smaludzi/projects/never/build_js'
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kuba--** [comment]
https://github.com/emscripten-core/emscripten/issues/10818

**Comment by kuba--** [comment]
I tested on `macOS (Catalina)` and on `Ubuntu Focal Fossa (development branch) / Linux e4fcd066bb8f 4.9.184-linuxkit`, with:
- gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- emcc (Emscripten gcc/clang-like replacement) 1.39.15
- cmake version 3.16.3

...and didn't have any problems to compile it to JS and to WASM.

**Comment by smaludzi** [comment]
Could you try with changes I made? I removed standard directories from cmake.

**Comment by kuba--** [comment]
Yes, I tried on the latest `wasm` branch.

**Pull request merged**
